[env:esp32s3_generic_n4r2]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
build_type = release
board_build.partitions = partitions_dfu.csv
board_upload.flash_size = 4MB
monitor_speed = 115200
upload_speed = 921600
extra_scripts = post:merge_firmware.py

build_flags =
    -Os
    -ffunction-sections
    -fdata-sections
